spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: CAFE
        password: 0911
    thymeleaf:
        prefix : classpath:templates/views/
        suffix : .html
    servlet:
        multipart:
            max-file-size: 104857600
            max-request-size: 10485760
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/cafe/bbs/**/dao/mapper/*.xml
    
app:
    multipart:
        base-dir: C:/uploadFiles
        obfuscation:
            enable: true
            hide-ext:
                enable: true
